location ^~ /.well-known/acme-challenge/ {
    proxy_pass http://zhixing-searxng-acme;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_connect_timeout 3s;
    proxy_read_timeout 5s;
}
